#! /bin/bash
DEPEND_LIBSRC=""
NULL_ARG_FLG="N"
SYS_LONG_BIT=0

BINARY_PATH="./bin"

HELP_MSG(){ 
    echo "select one algo interface to test" 
    echo "  -i algo type:[fib] [NULL] ..." 
}

compile_lib(){ 
    cd lib
    cmake -DLIBSRC=$DEPEND_LIBSRC
    make
    cd ..
}

compile(){ 
    cd build
    cmake .. -DLIBSRC=$DEPEND_LIBSRC -DLONGBIT=$SYS_LONG_BIT
    make
    cd ..
}

clean(){ 
    cd lib
    rm -rf CMakeFiles
    cd ../build
    rm -rf CMakeFiles
    rm cmake_install.cmake CMakeCache.txt Makefile
    rm -rf lib
}

check_env(){
    SYS_LONG_BIT=`getconf LONG_BIT`
    echo "111111 $SYS_LONG_BIT"
}

#pack(){}

start(){
    rm -rf bin
    mkdir bin
    rm -rf build
    mkdir build
}

check_env

while getopts "i:" var
do
    NULL_ARG_FLG="Y"
    case "$var" in
    i)
    if [ $OPTARG = "fib" ];then
        DEPEND_LIBSRC="fib"
    fi
    ;;
    h)
        HELP_MSG
        ;;
    ?)
        echo "bad param"
        HELP_MSG
    exit 1
    ;;
    esac
done

if [ ${NULL_ARG_FLG} = "N" ];then
    HELP_MSG
    exit 1
fi

#################################
#compile_lib

start

compile

#pack

clean
