#! /bin/bash
DEPEND_LIBSRC=""
HELP_MSG(){ 
    echo "select one algo interface to test" 
    echo "  -i algo type:[fib] [NULL] ..." 
}

compile_lib(){ 
    cd lib
    cmake -DLIBSRC=$DEPEND_LIBSRC
    make
    cd ..
}

compile(){ 
    cd build
    cmake .. -DLIBSRC=$DEPEND_LIBSRC
    make
    cd ..
}

clean(){ 
    cd lib
    rm -rf CMakeFiles
    rm cmake_install.cmake CMakeCache.txt Makefile
    cd ../build
    rm -rf CMakeFiles
    rm cmake_install.cmake CMakeCache.txt Makefile
    rm -rf lib
}

while getopts "i:" var
do
    case "$var" in
    i)
    if [ $OPTARG=="fib" ]
    then
        DEPEND_LIBSRC="fib"
    fi
    ;;
    h)
        HELP_MSG
        ;;
    ?)
        echo "bad param"
        HELP_MSG
    exit 1
    ;;
    esac
done

compile_lib

compile

clean
